### ISSUE TITLE
mime-type dependency not listed

### ISSUE THREAD

**Issue by glensc** [entu/entu-cms#7]
```
➔ yarn build
yarn run v1.16.0
$ ssg source/config.yaml
/app/.pnp.js:3839
    throw firstError;
    ^

Error: Package "entu-ssg@5.0.0" (via "/Users/glen/Library/Caches/Yarn/v4/npm-entu-ssg-5.0.0-c265dd778323695e0d3563d16127b7b43921e121/node_modules/entu-ssg/index.js") is trying to require the package "mime-types" (via "mime-types") without it being listed in its dependencies (async, autoprefixer-stylus, chokidar, fs-extra, html-minifier, js-yaml, jstransformer-markdown-it, jstransformer-stylus, klaw, lodash, markdown-it-attrs, markdown-it-multimd-table, markdown-it-sup, markdown-it, pug, request, stylus, uglify-js, entu-ssg)
    at makeError (/app/.pnp.js:55:17)
    at Object.resolveToUnqualified (/Users/glen/scm/ed/infra/docker-port-registry/.pnp.js:3577:17)
    at Object.resolveRequest (/app/.pnp.js:3648:31)
    at Function.Module._resolveFilename (/app/.pnp.js:3830:30)
    at Function.Module._load (/app/.pnp.js:3746:31)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/glen/Library/Caches/Yarn/v4/npm-entu-ssg-5.0.0-c265dd778323695e0d3563d16127b7b43921e121/node_modules/entu-ssg/index.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by glensc** [comment]
reproduce:

```
rm -rf test/
mkdir test
cd test/
yarn add entu-ssg@5.0.0
yarn --pnp
yarn run ssg bla.yml
```
